export const WSS_CONNECTION_REQUEST = 'WSS_CONNECTION_REQUEST';
export const WSS_CONNECTION_SUCCESS = 'WSS_CONNECTION_SUCCESS';
export const WSS_CONNECTION_ERROR = 'WSS_CONNECTION_ERROR';
export const WSS_CONNECTION_CLOSED = 'WSS_CONNECTION_CLOSED';
export const WSS_GET_MESSAGE = 'WSS_GET_MESSAGE';
export const WSS_SEND_MESSAGE = 'WSS_SEND_MESSAGE';
export const WSS_DELETE_ORDERS = 'WSS_DELETE_ORDERS';


export const wsActions = {
  wsInit: WSS_CONNECTION_REQUEST,
  wsSendMessage: WSS_SEND_MESSAGE,
  onOpen: WSS_CONNECTION_SUCCESS,
  onClose: WSS_CONNECTION_CLOSED,
  onError: WSS_CONNECTION_ERROR,
  onMessage: WSS_GET_MESSAGE,
};