export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_LOADING = 'GET_INGREDIENTS_LOADING';
export const ADD_BURGER_INGREDIENTS = 'ADD_BURGER_INGREDIENTS';
export const GET_COUNTER = 'GET_COUNTER';
