export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_LOADING = 'GET_INGREDIENTS_LOADING';
export const ADD_BURGER_INGREDIENTS = 'ADD_BURGER_INGREDIENTS';
export const GET_COUNTER = 'GET_COUNTER';
export const ADD_CONSTRUCTOR_ELEMENT = 'ADD_CONSTRUCTOR_ELEMENT';
export const REMOVE_CONSTRUCTOR_ELEMENT = 'REMOVE_CONSTRUCTOR_ELEMENT';
export const GET_DETAILS = 'GET_DETAILS';
export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';
